apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-block-pvc
  namespace: ceph
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-rbd-sc
