apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-sc
