---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-sc
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: fddc0aff-67cf-48d8-9704-04e14b897ed1
  fsName: K3S_CephFS
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph
  csi.storage.k8s.io/node-stage-secret-namespace: ceph
  subvolume: /volumes/_nogroup/csi/0b4c649e-6bee-4163-b12b-cddc5d3d9608
  mounter: kernel
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
