apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - "true"
      terminationGracePeriodSeconds: 15  
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10  
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10 
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.33.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: vaultwarden-storage
              mountPath: /data
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '1'
              memory: '1Gi'
      volumes:
        - name: vaultwarden-storage
          persistentVolumeClaim:
            claimName: vaultwarden-static-pvc

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vaultwarden-pdb
spec:
  maxUnavailable: 1  
  selector:
    matchLabels:
      app: vaultwarden

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: default
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: vaultwarden.simptum.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden-service
            port:
              number: 80
  tls:
  - hosts:
      - vaultwarden.simptum.net
    secretName: vaultwarden-ssl
