---
- name: Get device set up
  hosts: [k3s-01, k3s-02, k3s-03]
  become: yes
  become_user: root
  vars_files:
    - secret
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Update K3S config
      shell: |
        reboot now
