---
- name: Get device set up
  hosts: k3s-01
  become: yes
  become_user: root
  vars_files:
    - secret
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Update cache
      apt: 
        state: latest

    - name: Upgrade Packages
      apt: 
        upgrade: yes

    - name: Start timesyncd
      systemd_service:
        enabled: true
        state: started
        name: systemd-timesyncd.service

    - name: Copy ntp file
      template:
        src: ./templates/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf

    - name: Timedatectl
      shell: |
        timedatectl set-ntp true
        timedatectl set-timezone America/Los_Angeles

    - name: Remove swap
      shell: |
        if -f /swap.img; then
          swapoff /swap.img
          rm /swap.img
        fi

    - name: Install K3s
      shell: |
        ufw disable
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=servicelb --disable=traefik --cluster-init" sh -s - 

    - name: Copy token
      shell: |
        cat /var/lib/rancher/k3s/server/node-token
      register: k3s_output

    - name: Copy output to localhost
      local_action:
        module: copy
        content: "{{ k3s_output }}"
        dest: ./k3s_token.txt
