---
- name: Reboot entire cluster!
  hosts: k3s-nodes
  become: yes
  become_user: root
  vars_files:
    - secret
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Rebooting
      shell: |
        reboot now
