---
- name: Testing out ansible!
  hosts: k3s-nodes
  become: yes
  become_user: root
  vars_files:
    - secret
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Update cache
      apt: 
        state: latest
    - name: Apply sysctl.conf
      shell: |
        systemctl daemon-reload
        systemctl disable loadsysctl.service
    - name: Apply sysctl.conf
      shell: |
        reboot now
